---

- name: install Java
  package: name=openjdk-7-jre state=latest
  become: yes
  become_method: sudo

- name: check if elasticsearch is already installed
  shell: 'dpkg --list | grep -qs elasticsearch'
  register: elasticsearch_exists
  ignore_errors: yes

- name: download deb
  get_url: >
    url=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.1.1/elasticsearch-2.1.1.deb
    dest=/home/vagrant/
  when: elasticsearch_exists|failed

- name: install deb
  become: yes
  become_method: sudo
  apt: >
    deb=/home/vagrant/elasticsearch-2.1.1.deb
    state=present
  when: elasticsearch_exists|failed
