---

- name: Install vim
  package: name=vim state=latest
  become: yes
  become_method: sudo

- name: set vimrc
  copy: src=~/.vimrc dest=/home/vagrant/

# TODO - Check the vimrc file to figure out which one to run.
# lineinfile lets you check if a line exists, but tries to add it.
# There's probably something else that will just check.

# Assumes git
- name: Install Vundle
  git: >
    repo=https://github.com/VundleVim/Vundle.vim.git
    dest=~/.vim/bundle/Vundle.vim
    clone=yes

#- name: Install NeoBundle
#  git: >
#    rep=https://github.com/Shougo/neobundle.vim
#    dest=~/.vim/bundle/neobundle.vim
#    clone=yes
