---

# Lein

- name: install Java
  package: name=openjdk-7-jre state=latest
  become: yes
  become_method: sudo

- name: check if lein is already installed
  stat: path=/home/vagrant/.bin/lein
  register: lein

- name: debug gitconfig
  debug: var=lein

- name: create local bin
  file: path=/home/vagrant/.bin state=directory

- name: download lein
  get_url: >
    url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest=/home/vagrant/.bin
  when: lein.stat.exists == False

- name: change lien permissions
  file: path=/home/vagrant/.bin/lein mode=755
  when: lein.stat.exists == False

- name: update local path
  lineinfile: >
    dest=/home/vagrant/.bashrc
    state=present
    regexp="PATH=\$PATH"
    line="PATH=$PATH:~/.bin"
  when: lein.stat.exists == False

- name: run lein initially to get dependencies
  shell: /home/vagrant/.bin/lein
  when: lein.stat.exists == False
