---
- hosts: all
  remote_user: vagrant
  tasks:

  - name: install packages
    become: yes
    become_method: sudo
    apt: pkg={{item}} state=installed
    with_items:
        - openjdk-7-jre
        - git
        - vim
        - build-essential

  - include: tasks/vim.yml
  #- include: tasks/mongo.yml
  #- include: tasks/elasticsearch.yml
  #- include: tasks/npm.yml
  - include: tasks/lein.yml
